animal_organization/urls.py
from django.urls import path
from . import views

app_name = 'animal_organization'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
]

pet/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import CareCategoryViewSet,\
    PetViewSet,\
    PetCareLogViewSet,\
    PetOwnerGroupViewSet,\
    UserViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'pets', PetViewSet)
router.register(r'pet_owner_group', PetOwnerGroupViewSet)
router.register(r'care_category', CareCategoryViewSet)
router.register(r'pet_care_log', PetCareLogViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from pet.urls import router as pet_router
from blog.urls import router as blog_router


class DefaultRouter(routers.DefaultRouter):
    """
    Extends `DefaultRouter` class to add a method for extending url routes from another router.
    """
    def extend(self, app_router):
        """
        Extend the routes with url routes of the passed in router.

        Args:
             app_router: SimpleRouter instance containing route definitions.
        """
        self.registry.extend(app_router.registry)


router = DefaultRouter()
router.extend(pet_router)
router.extend(blog_router)

urlpatterns = [
    path('kawausoadmin/', admin.site.urls),
    path('red_list/', include('red_list.urls')),
    path('', include('animal_organization.urls')),
    path('api/v1/', include(router.urls)),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
    path('api/v1/auth/', include('djoser.urls.jwt')),
]

red_list/urls.py
from django.urls import path
from . import views

app_name = 'red_list'

urlpatterns = [
    path('', views.Top.as_view(), name='animal'),
    path('rule', views.Rule.as_view(), name='rule'),
]

red_list/models.py
from django.db import models

class Category(models.Model):

  name = models.CharField(max_length=32, blank=False, null=False)

  def __str__(self):
      return self.name


class Classification(models.Model):

  name = models.CharField(max_length=32, blank=False, null=False)

  def __str__(self):
      return self.name

class Animal(models.Model):

  japanese_name = models.CharField(max_length=256, blank=False, null=False)
  scientific_name = models.CharField(max_length=256, blank=False, null=True)
  category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
  classification = models.ForeignKey(Classification, on_delete=models.DO_NOTHING)

  def __str__(self):
      return self.japanese_name

red_list/forms.py
from django import forms

class AnimalForm(forms.ModelForm):
  pass

red_list/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from .models import Animal, Category, Classification
from django.db.models import Q
from functools import reduce
import operator


class Top(ListView):
    template_name = 'red_list/animal.html'
    model = Animal
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('query')

        if query and query.split() != []:
            category = Category.objects.filter(reduce(operator.or_, (Q(name__contains=keyword) for keyword in query.split())))
            classification = Classification.objects.filter(reduce(operator.or_, (Q(name__contains=keyword) for keyword in query.split())))
            object_list = Animal.objects.filter(
                reduce(operator.or_, (Q(japanese_name__contains=keyword) for keyword in query.split())) |
                reduce(operator.or_, (Q(scientific_name__contains=keyword) for keyword in query.split())) |
                Q(category__in=category)|
                Q(classification__in=classification)
                )
        else:
            object_list = Animal.objects.all()
        return object_list


class Rule(TemplateView):
    template_name = 'red_list/rule.html'

red_list/templates/red_list/animal.html
{% extends "red_list/base.html" %}
{% block content %}
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">レッドリスト検索</h1>
    <p class="fs-5 text-muted">日本のレッドリストを検索できます</p>
  </div>
  <main>
    <div class="row row-cols-1 row-cols-md-1 mb-3 text-center">
      <div class="col">
        <form class="d-flex" action="" method="get">
          <input class="form-control me-2" type="text" aria-label="検索" name="query" value="{{ request.GET.query }}">
          <button class="btn btn-lg btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    <div class="table-responsive text-nowrap mb-1">
      <table class="table">
        <thead>
          <tr>
            <th style="width: 25%;">和名</th>
            <th style="width: 40%;">学名</th>
            <th style="width: 25%;">カテゴリー</th>
            <th style="width: 10%;">分類</th>
          </tr>
        </thead>
        <tbody>
        {% for animal in object_list %}
          <tr>
            <th scope="row" class="text-start">{{ animal.japanese_name }}</th>
            <td>{{ animal.scientific_name}}</td>
            <td>{{ animal.category}}</td>
            <td>{{ animal.classification}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&query={{ request.GET.query }}">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
          {% if num <= page_obj.number|add:2 and num >= page_obj.number|add:-2 %}
            {% if page_obj.number == num %}
              <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ num }}&query={{ request.GET.query }}">{{ num }}</a></li>
            {% endif %}
          {% endif %}
        {% endfor %}
        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&query={{ request.GET.query }}">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </main>
{% endblock %}

red_list/templates/red_list/base.html
<!doctype html>
<html lang="ja">
<head>
  <!-- meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="動物病院の検索やレッドリストの検索ができます。自然や動物にやさしいこころを持ちましょう。">
  <!-- OG tags-->
  <meta property="og:title" content="biby" />
  <meta property="og:site_name" content="biby" />
  <meta property="og:description" content="動物病院の検索やレッドリストの検索ができます。自然や動物にやさしいこころを持ちましょう。" />
  <meta property="og:url" content="https://biby.live" />
  <meta property="og:type" content="website">
  <meta property="og:image" content="https://biby.live/static/red_list/images/ogp.jpg" />
  <meta property="og:locale" content="ja_JP" />
  <!-- Google / Search Engine Tags -->
  <meta itemprop="name" content="biby">
  <meta itemprop="description" content="動物病院の検索やレッドリストの検索ができます。自然や動物にやさしいこころを持ちましょう。">
  <meta itemprop="image" content="https://biby.live/static/red_list/images/ogp.jpg">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="https://biby.live">
  <meta property="og:type" content="website">
  <meta property="og:title" content="biby">
  <meta property="og:description" content="動物病院の検索やレッドリストの検索ができます。自然や動物にやさしいこころを持ちましょう。">
  <meta property="og:image" content="https://biby.live/static/red_list/images/ogp.jpg">
  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="biby">
  <meta name="twitter:description" content="動物病院の検索やレッドリストの検索ができます。自然や動物にやさしいこころを持ちましょう。">
  <meta name="twitter:image" content="https://biby.live/static/red_list/images/ogp.jpg">
  {% load static %}
  <!-- favicon -->
  <link rel="icon" type="image/png" href="{% static 'red_list/images/heart.png' %}" alt="biby">
  <link rel="apple-touch-icon" href="{% static 'red_list/images/heart.png' %}" alt="biby">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <title>biby</title>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-GB0Z4CDV3D"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-GB0Z4CDV3D');
  </script>
</head>
<body>
  <!-- bootstrap js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <div class="container py-3">
      <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-1 border-bottom">
          <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>biby</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
            <span class="fs-4">biby検索</span>
          </a>
          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'animal_organization:top' %}">ホスピタル</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'red_list:top' %}">レッドリスト</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="https://www.diary.biby.live/" target="_blank" rel="noopener noreferrer">bibyブログ</a>
          </nav>
        </div>
      </header>
      {% block content %}
      {% endblock %}
      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="{% static 'red_list/images/heart.svg' %}" alt="" width="24" height="19">
            <small class="d-block mb-3 text-muted">© 2021 biby</small>
          </div>
          <div class="col-6 col-md">
            <h5>運営者情報</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://alwaysblue.gatsbyjs.io/about" target="_blank" rel="noopener noreferrer">Aboutページ</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>サイト情報</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'red_list:rule' %}">利用規約</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>お問い合わせ</h5>
            <ul class="list-unstyled text-small">
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://forms.gle/EJdXYLNWbeLfCccm9" target="_blank" rel="noopener noreferrer">フォーム</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
</body>
<html>

red_list/templates/red_list/rule.html
{% extends "red_list/base.html" %}
{% block content %}
  <main>
    <h2 class="display-6 text-center mb-4">利用規約</h2>
    <h3>レッドリストの情報</h3>
    <p class="lead">本サイトの情報は環境省の提供するレッドリスト(https://ikilog.biodic.go.jp/Rdb/booklist)から引用しています。</p>
    <h3 class="mt-5">ご利用について</h3>
    <p class="lead">本サイトはレッドリストや動物病院の閲覧を目的とする場合にご自由にご利用いただけます。</p>
    <h3 class="mt-5">禁止行為</h3>
    <ul>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>不正アクセスまたはこれを試みる行為</li>
      <li>運営を妨害するような行為</li>
    </ul>
    <h3 class="mt-5">自然環境と動物にやさしい心を持ちましょう</h3>
    <ul>
      <li>やさしい心を持って自然に接してください。</li>
      <li>やさしい心を持って動物に接してください。</li>
      <li>資源は自然・動物を含めたみんなのものということを忘れないでください。</li>
      <li>自然・動物がいるから生きていられるということを忘れないでください。</li>
      <li>地球という大きなコミュニティの中にいることを意識してください。</li>
    </ul>
{% endblock %}